// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.get('WEB_API_KEY', fallback: ''),
    appId: dotenv.get('WEB_APP_ID', fallback: ''),
    messagingSenderId: dotenv.get('WEB_MESSAGING_SENDER_ID', fallback: ''),
    projectId: dotenv.get('WEB_PROJECT_ID', fallback: ''),
    authDomain: dotenv.get('WEB_AUTH_DOMAIN', fallback: ''),
    storageBucket: dotenv.get('WEB_STORAGE_BUCKET', fallback: ''),
    measurementId: dotenv.get('WEB_MEASUREMENT_ID', fallback: ''),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.get('ANDROID_API_KEY', fallback: ''),
    appId: dotenv.get('ANDROID_APP_ID', fallback: ''),
    messagingSenderId: dotenv.get('ANDROID_MESSAGING_SENDER_ID', fallback: ''),
    projectId: dotenv.get('ANDROID_PROJECT_ID', fallback: ''),
    storageBucket: dotenv.get('ANDROID_STORAGE_BUCKET', fallback: ''),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.get('IOS_API_KEY', fallback: ''),
    appId: dotenv.get('IOS_APP_ID', fallback: ''),
    messagingSenderId: dotenv.get('IOS_MESSAGING_SENDER_ID', fallback: ''),
    projectId: dotenv.get('IOS_PROJECT_ID', fallback: ''),
    storageBucket: dotenv.get('IOS_STORAGE_BUCKET', fallback: ''),
    iosBundleId: dotenv.get('IOS_BUNDLE_ID', fallback: ''),
  );
}
